<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $materials = [
    [
        'id_company' => 1,
        'name' => 'Harina de trigo',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 800, // precio por kilo
        'low_stock_threshold' => 10,
        'description' => 'Harina blanca para preparar masa de pizza.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Levadura seca',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 1500,
        'low_stock_threshold' => 5,
        'description' => 'Levadura seca para fermentación de la masa.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Agua potable',
        'type' => 'material',
        'unit_of_measure' => 'litro',
        'purchase_price' => 100,
        'low_stock_threshold' => 50,
        'description' => 'Agua para preparar masa y limpieza.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Sal',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 200,
        'low_stock_threshold' => 5,
        'description' => 'Sal común para la masa y condimentar.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Aceite de oliva',
        'type' => 'material',
        'unit_of_measure' => 'litro',
        'purchase_price' => 4000,
        'low_stock_threshold' => 5,
        'description' => 'Aceite de oliva para la masa y decoración.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Salsa de tomate',
        'type' => 'material',
        'unit_of_measure' => 'litro',
        'purchase_price' => 1800,
        'low_stock_threshold' => 10,
        'description' => 'Salsa de tomate natural para base de pizza.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Queso mozzarella',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 5000,
        'low_stock_threshold' => 8,
        'description' => 'Queso mozzarella rallado o en láminas.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Pepperoni',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 7000,
        'low_stock_threshold' => 5,
        'description' => 'Pepperoni en rodajas para topping.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Jamón',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 6000,
        'low_stock_threshold' => 6,
        'description' => 'Jamón cocido en láminas para pizza.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Piña',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 3000,
        'low_stock_threshold' => 5,
        'description' => 'Piña en trozos para pizza hawaiana.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Champiñones',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 3500,
        'low_stock_threshold' => 5,
        'description' => 'Champiñones frescos en láminas para pizza.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Pimientos',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 3200,
        'low_stock_threshold' => 5,
        'description' => 'Pimientos en tiras para pizza vegetariana.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Aceitunas negras',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 4000,
        'low_stock_threshold' => 5,
        'description' => 'Aceitunas negras en rodajas para topping.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Queso azul',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 6000,
        'low_stock_threshold' => 5,
        'description' => 'Queso azul para pizza cuatro quesos.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Queso parmesano',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 6500,
        'low_stock_threshold' => 5,
        'description' => 'Queso parmesano rallado para pizza.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Cebolla morada',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 2500,
        'low_stock_threshold' => 5,
        'description' => 'Cebolla morada fresca para toppings.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
    [
        'id_company' => 1,
        'name' => 'Pollo cocido',
        'type' => 'material',
        'unit_of_measure' => 'kg',
        'purchase_price' => 6500,
        'low_stock_threshold' => 5,
        'description' => 'Pollo cocido desmenuzado para pizza BBQ.',
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => null,
    ],
];
foreach ($materials as $material) {
            DB::table('materials')->insert(array_merge($material));
        }
    }
}
