<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductServiceSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
     public function run()
    {
        $products = [
            // PIZZAS
            [
                'id_company' => 1,
                'name' => 'Pizza Margarita',
                'description' => 'Pizza clásica con salsa de tomate, mozzarella y albahaca fresca.',
                'sale_price' => 8500,
                'purchase_price' => 4500,
                'SKU' => 'PZ001',
                'type' => 'producto',
                'is_fabricable' => true,
                'is_resellable' => false,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '5000',
                'markup_percentage' => '70',
            ],
            [
                'id_company' => 1,
                'name' => 'Pizza Pepperoni',
                'description' => 'Pizza con pepperoni, mozzarella y salsa de tomate.',
                'sale_price' => 9500,
                'purchase_price' => 5000,
                'SKU' => 'PZ002',
                'type' => 'producto',
                'is_fabricable' => true,
                'is_resellable' => false,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '5500',
                'markup_percentage' => '70',
            ],
            [
                'id_company' => 1,
                'name' => 'Pizza Hawaiana',
                'description' => 'Pizza con jamón, piña y queso mozzarella.',
                'sale_price' => 9700,
                'purchase_price' => 5200,
                'SKU' => 'PZ003',
                'type' => 'producto',
                'is_fabricable' => true,
                'is_resellable' => false,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '5600',
                'markup_percentage' => '73',
            ],
            [
                'id_company' => 1,
                'name' => 'Pizza Vegetariana',
                'description' => 'Pizza con champiñones, pimientos, cebolla y aceitunas.',
                'sale_price' => 9000,
                'purchase_price' => 4800,
                'SKU' => 'PZ004',
                'type' => 'producto',
                'is_fabricable' => true,
                'is_resellable' => false,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '5200',
                'markup_percentage' => '72',
            ],
            [
                'id_company' => 1,
                'name' => 'Pizza Cuatro Quesos',
                'description' => 'Pizza con mezcla de quesos: mozzarella, azul, parmesano y cheddar.',
                'sale_price' => 9800,
                'purchase_price' => 5500,
                'SKU' => 'PZ005',
                'type' => 'producto',
                'is_fabricable' => true,
                'is_resellable' => false,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '5600',
                'markup_percentage' => '75',
            ],
            [
                'id_company' => 1,
                'name' => 'Pizza BBQ Pollo',
                'description' => 'Pizza con trozos de pollo, salsa BBQ y cebolla morada.',
                'sale_price' => 9900,
                'purchase_price' => 5700,
                'SKU' => 'PZ006',
                'type' => 'producto',
                'is_fabricable' => true,
                'is_resellable' => false,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '5800',
                'markup_percentage' => '71',
            ],

            // PRODUCTOS ADICIONALES
            [
                'id_company' => 1,
                'name' => 'Nuggets de Pollo',
                'description' => 'Porción de 6 nuggets de pollo.',
                'sale_price' => 4000,
                'purchase_price' => 2000,
                'SKU' => 'AD001',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'porción',
                'average_cost' => '2200',
                'markup_percentage' => '80',
            ],
            [
                'id_company' => 1,
                'name' => 'Bebida Gaseosa 500ml',
                'description' => 'Botella de bebida gaseosa de 500ml.',
                'sale_price' => 2000,
                'purchase_price' => 1000,
                'SKU' => 'AD002',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '1100',
                'markup_percentage' => '100',
            ],
            [
                'id_company' => 1,
                'name' => 'Papas fritas clásicas',
                'description' => 'Porción de papas fritas crocantes.',
                'sale_price' => 2500,
                'purchase_price' => 1200,
                'SKU' => 'AD003',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'porción',
                'average_cost' => '1200',
                'markup_percentage' => '108',
            ],
            [
                'id_company' => 1,
                'name' => 'Papas fritas con queso cheddar',
                'description' => 'Papas fritas bañadas en queso cheddar.',
                'sale_price' => 2900,
                'purchase_price' => 1500,
                'SKU' => 'AD004',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'porción',
                'average_cost' => '1500',
                'markup_percentage' => '93',
            ],
            [
                'id_company' => 1,
                'name' => 'Aros de cebolla',
                'description' => 'Porción de aros de cebolla empanizados.',
                'sale_price' => 2700,
                'purchase_price' => 1300,
                'SKU' => 'AD005',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'porción',
                'average_cost' => '1300',
                'markup_percentage' => '108',
            ],
            [
                'id_company' => 1,
                'name' => 'Palitos de queso mozzarella',
                'description' => 'Palitos fritos rellenos de queso mozzarella.',
                'sale_price' => 3200,
                'purchase_price' => 1600,
                'SKU' => 'AD006',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'porción',
                'average_cost' => '1600',
                'markup_percentage' => '100',
            ],
            [
                'id_company' => 1,
                'name' => 'Nachos con queso',
                'description' => 'Nachos servidos con salsa de queso caliente.',
                'sale_price' => 3100,
                'purchase_price' => 1500,
                'SKU' => 'AD007',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'porción',
                'average_cost' => '1500',
                'markup_percentage' => '107',
            ],
            [
                'id_company' => 1,
                'name' => 'Bastones de pan con ajo',
                'description' => 'Bastones de pan artesanal con mantequilla y ajo.',
                'sale_price' => 2800,
                'purchase_price' => 1300,
                'SKU' => 'AD008',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '1300',
                'markup_percentage' => '115',
            ],
            [
                'id_company' => 1,
                'name' => 'Empanaditas de jamón y queso',
                'description' => 'Mini empanadas horneadas de jamón y queso.',
                'sale_price' => 3000,
                'purchase_price' => 1400,
                'SKU' => 'AD009',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '1400',
                'markup_percentage' => '114',
            ],
            [
                'id_company' => 1,
                'name' => 'Deditos de queso',
                'description' => 'Deditos fritos rellenos de queso fundido.',
                'sale_price' => 3100,
                'purchase_price' => 1500,
                'SKU' => 'AD010',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'porción',
                'average_cost' => '1500',
                'markup_percentage' => '107',
            ],
            [
                'id_company' => 1,
                'name' => 'Tequeños',
                'description' => 'Rollitos de masa frita rellenos de queso blanco.',
                'sale_price' => 3300,
                'purchase_price' => 1600,
                'SKU' => 'AD011',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'porción',
                'average_cost' => '1600',
                'markup_percentage' => '106',
            ],
            [
                'id_company' => 1,
                'name' => 'Papas bravas con alioli',
                'description' => 'Papas picantes con alioli casero.',
                'sale_price' => 2900,
                'purchase_price' => 1400,
                'SKU' => 'AD012',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'porción',
                'average_cost' => '1400',
                'markup_percentage' => '107',
            ],
            [
                'id_company' => 1,
                'name' => 'Bebida Gaseosa 1.5L',
                'description' => 'Botella grande de gaseosa.',
                'sale_price' => 3000,
                'purchase_price' => 1500,
                'SKU' => 'AD013',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'unidad',
                'average_cost' => '1500',
                'markup_percentage' => '100',
            ],
            [
                'id_company' => 1,
                'name' => 'Jugo natural de naranja',
                'description' => 'Jugo natural exprimido.',
                'sale_price' => 2800,
                'purchase_price' => 1400,
                'SKU' => 'AD014',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'vaso',
                'average_cost' => '1400',
                'markup_percentage' => '100',
            ],
            [
                'id_company' => 1,
                'name' => 'Jugo natural de frutilla',
                'description' => 'Jugo de frutilla 100% natural.',
                'sale_price' => 2800,
                'purchase_price' => 1400,
                'SKU' => 'AD015',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'vaso',
                'average_cost' => '1400',
                'markup_percentage' => '100',
            ],
            [
                'id_company' => 1,
                'name' => 'Agua mineral sin gas',
                'description' => 'Botella de agua purificada 500ml.',
                'sale_price' => 1500,
                'purchase_price' => 800,
                'SKU' => 'AD016',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'botella',
                'average_cost' => '800',
                'markup_percentage' => '88',
            ],
            [
                'id_company' => 1,
                'name' => 'Agua mineral con gas',
                'description' => 'Botella de agua con gas 500ml.',
                'sale_price' => 1600,
                'purchase_price' => 900,
                'SKU' => 'AD017',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'botella',
                'average_cost' => '900',
                'markup_percentage' => '77',
            ],
            [
                'id_company' => 1,
                'name' => 'Té frío de limón',
                'description' => 'Bebida de té con sabor a limón.',
                'sale_price' => 2000,
                'purchase_price' => 1000,
                'SKU' => 'AD018',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'vaso',
                'average_cost' => '1000',
                'markup_percentage' => '100',
            ],
            [
                'id_company' => 1,
                'name' => 'Té frío de durazno',
                'description' => 'Bebida de té con sabor a durazno.',
                'sale_price' => 2000,
                'purchase_price' => 1000,
                'SKU' => 'AD019',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'vaso',
                'average_cost' => '1000',
                'markup_percentage' => '100',
            ],
            [
                'id_company' => 1,
                'name' => 'Cerveza artesanal 330ml',
                'description' => 'Botella de cerveza artesanal nacional.',
                'sale_price' => 3500,
                'purchase_price' => 1800,
                'SKU' => 'AD020',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'botella',
                'average_cost' => '1800',
                'markup_percentage' => '94',
            ],
            [
                'id_company' => 1,
                'name' => 'Cerveza sin alcohol',
                'description' => 'Cerveza sin alcohol para todos los gustos.',
                'sale_price' => 3200,
                'purchase_price' => 1600,
                'SKU' => 'AD021',
                'type' => 'producto',
                'is_fabricable' => false,
                'is_resellable' => true,
                'is_rentable' => false,
                'unit_of_measure' => 'botella',
                'average_cost' => '1600',
                'markup_percentage' => '100',
            ],
        ];

        foreach ($products as $product) {
            DB::table('products_services')->insert(array_merge($product, [
                'height' => null,
                'weight' => null,
                'width' => null,
                'length' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ]));
        }
    }
}
